### ISSUE TITLE
[Feature request] Don't ask people to code entire apps for you

### ISSUE THREAD

**Issue by RedGuy12** [maunium/dontasktoask.com#97]
Every now and then, I see people asking other people to make entire apps/websites/games/etc for them. It would be nice if this website mentioned that you shouldn't do that.

**Comment by j4cegh** [comment]
Correct me if I'm wrong, but that really is not the point of the site...

**Comment by mtatko** [comment]
As far as I'm concerned, the point of the site is to educate why you should ask questions directly instead of asking to ask. In fact, people asking others to make entire projects for them is also quite a frequent problem, however I don't see any connection to dontasktoask.com.

What I would suggest is you making a such website. We would be more than glad to include it in `Other simillar problems` section of our site

**Comment by j4cegh** [comment]
@RedGuy12 ^^ this suggestion of mtatko is perfect; You can make such a site and we'll be more than happy to help with adding a redirect to your site. :)
